worker_processes  1;

events {
    worker_connections  1024;
}

http {
  server {
    listen 80;
    sendfile        on;
    keepalive_timeout  65;
    gzip  on;
    server_name lnewtium.com;
    location /cloud/api {
        proxy_pass http://backend:5000;
    }
    location /cloud {
        proxy_pass http://frontend:80;
    }
  }
}