export const uiStrings = {
  delete: "Delete",
  open: "Open",
  create: "Create",
  decrypt: "Decrypt",
  encrypt: "Encrypt",
  home: "Home",
  close: "Close",
  logout: "Logout",
  filesNotFound: "Files not found",
  dropFilesThere: "Drop files there",
  createFolder: "Create folder",
  uploadFile: "Upload file",
  sortByName: "By name",
  sortByType: "By type",
  sortByDate: "By date",
  search: "Search...",
  provideEncryptionKey: "Provide encryption passphrase",
  enterEncryptionKey: "Enter encryption key",
  createNewFolder: "Create new folder",
  enterFolderName: "Enter folder name",
  loginTitle: "Authorization",
  registrationTitle: "New account",
  enterEmail: "Email",
  enterPassword: "Password",
  submit: "submit",
  login: "Login",
  registration: "Registration",
  actions: "Actions",
};
